name: Code Coverage with Codecov

on:
  push:
    branches:
      - coverage
  pull_request:
    branches:
      - main
jobs:
  Javascore-Coverage:
    runs-on: ubuntu-latest
    container:
      image: iconbridge/build
      options: --user 1001
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Javascore BMC coverage
      working-directory: ./javascore/bmc
      run: |
        gradle test

    - name: Javascore BMV coverage
      working-directory: ./javascore/bmv
      continue-on-error: true
      run: |
        gradle test

    - name: Javascore BSH coverage
      working-directory: ./javascore/bsh
      run: |
        gradle test

    - name: Javascore nativecoin coverage
      working-directory: ./javascore/nativecoin
      run: |
        gradle test

    - name: Javascore test-lib coverage
      working-directory: ./javascore/test-lib
      run: |
        gradle test
    - name: Javascore xcall coverage
      working-directory: ./javascore/test-lib
      run: |
        gradle test

    - name: GO test common
      working-directory: ./common
      run: |
        go test ./... -race -covermode=atomic -coverprofile=coverage.out || exit 0

    - name: Solidity BMC coverage
      working-directory: ./solidity/bmc
      run: |
        yarn install
        truffle run coverage || exit 0 # Bug on truffle to compile while running coverage and it fails, so exit 0
    - name: Solidity BMV coverage
      working-directory: ./solidity/bmc
      run: |
        yarn install
        truffle run coverage || exit 0

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
